#!/bin/sh -x

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

LWDIR="${SCRIPTPATH}/../share/lispworks"
export HOME=$LWDIR
export XDG_CACHE_HOME="${LWDIR}/.cache/"

# If license variables are available, pass them explicitly to avoid relying on
# an existing lwlicense file in the sysroot.
LIC_ARGS=""
if [ -n "${LW_SERIAL}" ] && [ -n "${LW_KEY}" ]; then
    LIC_ARGS="--lwlicenseserial ${LW_SERIAL} --lwlicensekey ${LW_KEY}"
fi

# FIXME: we install LW binary without exec permissions and set them here
# because otherwise something in Yocto changes its dynamic interpreter
# (ld-linux) to x86 arch during sysroot population stage
chmod 755 $LWDIR/lispworks-8-1-0-arm-linux

qemu-arm -L $LWDIR/qemu/arm-linux-libs $LWDIR/lispworks-8-1-0-arm-linux $LIC_ARGS "$@"
