#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

LWDIR="${SCRIPTPATH}/../share/lispworks"
export HOME=$LWDIR
export XDG_CACHE_HOME="${LWDIR}/.cache/"
export LD_LIBRARY_PATH="${PWD}/../recipe-sysroot/usr/lib"

# FIXME: we install LW binary without exec permissions and set them here
# because otherwise something in Yocto changes its dynamic interpreter
# (ld-linux) to x86 arch during sysroot population stage
chmod 755 $LWDIR/lispworks-8-0-0-arm-linux

qemu-arm -L $LWDIR/qemu/arm-linux-libs $LWDIR/lispworks-8-0-0-arm-linux "$@"
